version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3.1

executors:
  default:
    docker:
      - image: docker:17.05.0-ce-git

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - kubernetes/install-kubectl
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Configure variable
          command: |
            echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> .env
            echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> .env
            echo DOCKER_HUB_PASSWORD=$DOCKER_HUB_PASSWORD >> .env
            echo DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME >> .env
            cat .env
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/ml-classification.tar
      - run:
          name: Docker login
          command: |
            docker login -u "$DOCKER_HUB_USERNAME" -p $(echo "$DOCKER_HUB_PASSWORD")
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/ml-classification.tar | true
      - run:
          name: Build application Docker image
          command: docker build --cache-from=ml-classification -t ml-classification .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/ml-classification.tar ml-classification
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/ml-classification.tar
      - run:
          name: Push Docker Image
          command: |
            docker tag ml-classification phamanhtuan221995/ml-classification
            docker push phamanhtuan221995/ml-classification
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: ./kubernetes/deployment.yaml
          resource-name: deployment/ml-classification
          show-kubectl-command: true
      - run:
          name: Test cluster
          command: |
            kubectl get nodes
            kubectl get deployment
            kubectl get pod -o wide
            kubectl get services
      - run:
          name: Cleaning up
          command: docker system prune

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          cluster-name: CapstoneEKS-ouGTG7ol8WdS
          filters:
            branches:
              only:
                - master
